#!/bin/bash

generate()
{
	if [ $# -eq 0 ] ; then
		echo "No argument found, please input a number."
		exit 1
	fi
	if [ ! "$1" -eq "$1" ] ; then
		echo "input numbers only"
	fi
	mkdir arb1 2>/dev/null
	mkdir arb2 2>/dev/null
	for ((i=1; i < "$1" ; i++)); do
		touch check_"$i".txt
		echo "this is the" "$i""th file" > check_"$i".txt
		mv check_"$i".txt arb1
	done
	cp -rp arb1/* arb2
}

generate 20
