#!/bin/bash

source ./iterator
source ./comparator

echo "Starting..."

pathToDirectoryA='./arb1'
pathToDirectoryB='./arb2'
pathToDataBaseS='./.database'

pathToDirectoryA=$(realpath $pathToDirectoryA)
pathToDirectoryB=$(realpath $pathToDirectoryB)

pathToDataBaseS=$(realpath $pathToDataBaseS)
pathToDataBaseA='/dev/shm/SyncDataBaseA'
pathToDataBaseB='/dev/shm/SyncDataBaseB'

#Clear databases :
> $pathToDataBaseA
> $pathToDataBaseB

echo "Syncing ""$pathToDirectoryA"" and ""$pathToDirectoryB"
echo `awk 'NR==1' $pathToDataBaseS`
echo `awk 'NR==2' $pathToDataBaseS`

#Iterate and create database files in multi processing :
iterate $pathToDirectoryA $pathToDataBaseA $pathToDirectoryA"/" &
iterate $pathToDirectoryB $pathToDataBaseB $pathToDirectoryB"/" &
wait

compare $pathToDataBaseA $pathToDataBaseS $pathToDataBaseB

echo "Done."

#rm $pathToDataBaseA
#rm $pathToDataBaseB
